apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
  - cluster-issuer.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.12.0/cert-manager.crds.yaml
  - helm.yaml
configMapGenerator:
  - name: cert-manager-base-values
    files:
      - values.yaml